default:
  server:
    port: 3000
  website:
    title: 'spmjs'
    GA: ''
  wwwroot: 'data'
  authorize: 'github' # or github
  reservedWords: 'root admin administrator bot robot master webmaster account people user users project projects search action favorite like love team teams group groups organization organizations package packages org com net help doc docs demo document documentation blog bbs forum forums static assets repository public private mac windows ios lab callback'
