default:
  server:
    port: 3000
  website:
    title: 'spmjs'
    GA: '' # Google Analytics ID
  wwwroot: 'data'
  authorize:
    type: 'anonymous' # or github
    # https://github.com/organizations/spmjs/settings/applications
    # for github authorize type
    clientId: ''
    clientSecret: ''
    baseURL: 'http://127.0.0.1:3000'
  reservedWords: 'root admin administrator bot www robot master webmaster account people user users project projects search action favorite like love team teams group groups organization organizations package packages org com net help doc docs demo document documentation blog bbs forum forums static assets repository public private mac windows ios lab callback tag tags badge unknown undefined null node spm spmjs owner ownership'
